### ISSUE TITLE
Is there a way to force libsacdread to alternative directory?

### ISSUE THREAD

**Issue by vincentneo** [sacd-ripper/sacd-ripper#105]
I keep getting ` libsacdread: Can't stat /dev/cdrom` when the directory should be /dev/sr0 when running sacd_extract meant to extract from sacd player.

How can I change it?

**Comment by setmind** [comment]
Just use the -i option like this:
-i /dev/sr0

**Comment by vincentneo** [comment]
Alright... I can't solve the underlying problem anyway, so I'll close this.
